#!/bin/bash

set -eu

cd $(dirname $0)

TEMPDIR=$(tempfile)
cleanup () {
    local rv=$?
    rm -rf -- $TEMPDIR
    exit $rv
}
trap cleanup EXIT

DOCDIR=apps/blizanci/doc
rebar3 edoc

rm -rf $TEMPDIR
cp -a $DOCDIR $TEMPDIR
git checkout gh-pages
cp -a $TEMPDIR/* .
git status
